"""Generate responsive assets without adding lossy recompression (requires Pillow).

Run from any directory: python angular/scripts/optimize-images.py
Original assets remain available. Full-size replacements must decode identically;
smaller candidates use Lanczos resizing and lossless WebP encoding. A candidate
larger than the full-size source is omitted rather than increasing the payload.
"""

from io import BytesIO
import json
from pathlib import Path
import re

from PIL import Image, ImageOps


ROOT = Path(__file__).resolve().parents[1]
PUBLIC = ROOT / "public"
OUTPUT = PUBLIC / "assets/images/optimized"
MANIFEST = ROOT / "src/app/core/media/image-manifest.ts"
WIDTHS = (480, 800, 1200, 1600)


def webp_bytes(image):
    buffer = BytesIO()
    # In lossless mode, quality controls compression effort, not pixel fidelity.
    image.save(buffer, "WEBP", lossless=True, quality=80, method=4,
               icc_profile=image.info.get("icc_profile", b""))
    data = buffer.getvalue()
    with Image.open(BytesIO(data)) as decoded:
        assert decoded.convert(image.mode).tobytes() == image.tobytes()
    return data


def generate():
    project_source = (ROOT / "src/app/core/staticComponents/project/project.component.ts").read_text(encoding="utf-8")
    urls = sorted(set(re.findall(r"image: '(/assets/images/[^']+)'", project_source)) | {
        "/assets/images/cgPic.JPG", "/assets/images/fuji-water-fallback.jpg"
    })
    manifest = {}
    original_total = full_total = mobile_total = 0
    full_replacements = 0
    for url in urls:
        source = PUBLIC / url.lstrip("/")
        with Image.open(source) as opened:
            image = ImageOps.exif_transpose(opened)
            image = image.convert("RGBA" if "A" in image.getbands() else "RGB")
        width, height = image.size
        relative = Path(url).relative_to("/assets/images").with_suffix("")
        destination = OUTPUT / relative
        destination.parent.mkdir(parents=True, exist_ok=True)
        full_data = webp_bytes(image)
        original_bytes = source.stat().st_size
        full_url = url
        full_bytes = original_bytes
        if len(full_data) < original_bytes:
            full_path = destination.with_name(f"{destination.name}-{width}.webp")
            full_path.write_bytes(full_data)
            full_url = "/" + full_path.relative_to(PUBLIC).as_posix()
            full_bytes = len(full_data)
            full_replacements += 1
        candidates = []
        for target_width in WIDTHS:
            if target_width >= width:
                continue
            scaled = image.resize((target_width, round(height * target_width / width)), Image.Resampling.LANCZOS)
            data = webp_bytes(scaled)
            if len(data) >= full_bytes:
                continue
            path = destination.with_name(f"{destination.name}-{target_width}.webp")
            path.write_bytes(data)
            candidates.append((target_width, "/" + path.relative_to(PUBLIC).as_posix(), len(data)))
        candidates.append((width, full_url, full_bytes))
        manifest[url] = {
            "src": full_url,
            "srcset": ", ".join(f"{path} {size}w" for size, path, _ in candidates),
            "width": width,
            "height": height,
        }
        original_total += original_bytes
        full_total += full_bytes
        mobile_total += next((size for candidate_width, _, size in candidates if candidate_width >= 800), full_bytes)

    MANIFEST.parent.mkdir(parents=True, exist_ok=True)
    MANIFEST.write_text(
        "// Generated by scripts/optimize-images.py. Do not edit by hand.\n"
        "export interface ResponsiveImage {\n  readonly src: string;\n  readonly srcset: string;\n  readonly width: number;\n  readonly height: number;\n}\n\n"
        "export const IMAGE_MANIFEST: Readonly<Record<string, ResponsiveImage>> = "
        + json.dumps(manifest, indent=2) + ";\n",
        encoding="utf-8", newline="\n"
    )
    with Image.open(PUBLIC / "favicon.ico") as icon:
        icon = icon.convert("RGBA")
        icon.save(PUBLIC / "favicon.png", optimize=True)
        with Image.open(PUBLIC / "favicon.png") as decoded:
            assert icon.tobytes() == decoded.convert("RGBA").tobytes()
    print(json.dumps({
        "images": len(urls), "lossless_full_size_replacements": full_replacements,
        "original_bytes": original_total, "full_size_selected_bytes": full_total,
        "800px_or_next_candidate_bytes": mobile_total,
        "favicon_original_bytes": (PUBLIC / "favicon.ico").stat().st_size,
        "favicon_png_bytes": (PUBLIC / "favicon.png").stat().st_size,
        "verification": "Every generated WebP matches its input pixels; favicon pixels match original."
    }, indent=2))


if __name__ == "__main__":
    generate()
