// Generated by scripts/optimize-images.py. Do not edit by hand.
export interface ResponsiveImage {
  readonly src: string;
  readonly srcset: string;
  readonly width: number;
  readonly height: number;
}

export const IMAGE_MANIFEST: Readonly<Record<string, ResponsiveImage>> = {
  "/assets/images/ACIPics/0dashbaordOverview.jpg": {
    "src": "/assets/images/ACIPics/0dashbaordOverview.jpg",
    "srcset": "/assets/images/optimized/ACIPics/0dashbaordOverview-480.webp 480w, /assets/images/ACIPics/0dashbaordOverview.jpg 952w",
    "width": 952,
    "height": 842
  },
  "/assets/images/ACIPics/1dbPortfolios.png": {
    "src": "/assets/images/optimized/ACIPics/1dbPortfolios-570.webp",
    "srcset": "/assets/images/optimized/ACIPics/1dbPortfolios-570.webp 570w",
    "width": 570,
    "height": 370
  },
  "/assets/images/ACIPics/2portfolioOverview.jpg": {
    "src": "/assets/images/ACIPics/2portfolioOverview.jpg",
    "srcset": "/assets/images/ACIPics/2portfolioOverview.jpg 610w",
    "width": 610,
    "height": 357
  },
  "/assets/images/ACIPics/3allocationBreakdown.jpg": {
    "src": "/assets/images/ACIPics/3allocationBreakdown.jpg",
    "srcset": "/assets/images/ACIPics/3allocationBreakdown.jpg 582w",
    "width": 582,
    "height": 657
  },
  "/assets/images/ACIPics/4CreatePortfolioManually.png": {
    "src": "/assets/images/optimized/ACIPics/4CreatePortfolioManually-1006.webp",
    "srcset": "/assets/images/optimized/ACIPics/4CreatePortfolioManually-480.webp 480w, /assets/images/optimized/ACIPics/4CreatePortfolioManually-1006.webp 1006w",
    "width": 1006,
    "height": 441
  },
  "/assets/images/ACIPics/5CreatePortfolioGenerate.jpg": {
    "src": "/assets/images/ACIPics/5CreatePortfolioGenerate.jpg",
    "srcset": "/assets/images/optimized/ACIPics/5CreatePortfolioGenerate-480.webp 480w, /assets/images/ACIPics/5CreatePortfolioGenerate.jpg 906w",
    "width": 906,
    "height": 462
  },
  "/assets/images/ACIPics/6Simulator.jpg": {
    "src": "/assets/images/ACIPics/6Simulator.jpg",
    "srcset": "/assets/images/optimized/ACIPics/6Simulator-480.webp 480w, /assets/images/ACIPics/6Simulator.jpg 1152w",
    "width": 1152,
    "height": 775
  },
  "/assets/images/ACIPics/8aiChat2LikeExpert.jpg": {
    "src": "/assets/images/ACIPics/8aiChat2LikeExpert.jpg",
    "srcset": "/assets/images/ACIPics/8aiChat2LikeExpert.jpg 405w",
    "width": 405,
    "height": 455
  },
  "/assets/images/ACIPics/aiChat1Like5.jpg": {
    "src": "/assets/images/ACIPics/aiChat1Like5.jpg",
    "srcset": "/assets/images/ACIPics/aiChat1Like5.jpg 410w",
    "width": 410,
    "height": 455
  },
  "/assets/images/CGSitePhotos/0raspby.jpg": {
    "src": "/assets/images/CGSitePhotos/0raspby.jpg",
    "srcset": "/assets/images/optimized/CGSitePhotos/0raspby-480.webp 480w, /assets/images/optimized/CGSitePhotos/0raspby-800.webp 800w, /assets/images/CGSitePhotos/0raspby.jpg 2048w",
    "width": 2048,
    "height": 2048
  },
  "/assets/images/CGSitePhotos/1RPiConnect.png": {
    "src": "/assets/images/optimized/CGSitePhotos/1RPiConnect-597.webp",
    "srcset": "/assets/images/optimized/CGSitePhotos/1RPiConnect-597.webp 597w",
    "width": 597,
    "height": 342
  },
  "/assets/images/CGSitePhotos/2NameCheap.png": {
    "src": "/assets/images/optimized/CGSitePhotos/2NameCheap-647.webp",
    "srcset": "/assets/images/optimized/CGSitePhotos/2NameCheap-647.webp 647w",
    "width": 647,
    "height": 670
  },
  "/assets/images/CGSitePhotos/3Cloudflare.png": {
    "src": "/assets/images/optimized/CGSitePhotos/3Cloudflare-1047.webp",
    "srcset": "/assets/images/optimized/CGSitePhotos/3Cloudflare-480.webp 480w, /assets/images/optimized/CGSitePhotos/3Cloudflare-1047.webp 1047w",
    "width": 1047,
    "height": 547
  },
  "/assets/images/CGSitePhotos/4LiveWebsite.png": {
    "src": "/assets/images/optimized/CGSitePhotos/4LiveWebsite-587.webp",
    "srcset": "/assets/images/optimized/CGSitePhotos/4LiveWebsite-587.webp 587w",
    "width": 587,
    "height": 660
  },
  "/assets/images/PayCoPilotPic/AiArchitecture.jpg": {
    "src": "/assets/images/PayCoPilotPic/AiArchitecture.jpg",
    "srcset": "/assets/images/PayCoPilotPic/AiArchitecture.jpg 687w",
    "width": 687,
    "height": 572
  },
  "/assets/images/PayCoPilotPic/CmdTermainls4TwoSeperateSystems.png": {
    "src": "/assets/images/optimized/PayCoPilotPic/CmdTermainls4TwoSeperateSystems-1917.webp",
    "srcset": "/assets/images/optimized/PayCoPilotPic/CmdTermainls4TwoSeperateSystems-480.webp 480w, /assets/images/optimized/PayCoPilotPic/CmdTermainls4TwoSeperateSystems-1917.webp 1917w",
    "width": 1917,
    "height": 1077
  },
  "/assets/images/PayCoPilotPic/DatabasePSQLDuringDemo.jpg": {
    "src": "/assets/images/PayCoPilotPic/DatabasePSQLDuringDemo.jpg",
    "srcset": "/assets/images/optimized/PayCoPilotPic/DatabasePSQLDuringDemo-480.webp 480w, /assets/images/PayCoPilotPic/DatabasePSQLDuringDemo.jpg 1117w",
    "width": 1117,
    "height": 752
  },
  "/assets/images/PayCoPilotPic/GenSys0.jpg": {
    "src": "/assets/images/PayCoPilotPic/GenSys0.jpg",
    "srcset": "/assets/images/PayCoPilotPic/GenSys0.jpg 612w",
    "width": 612,
    "height": 587
  },
  "/assets/images/PayCoPilotPic/GenSys1GeneratedInput.jpg": {
    "src": "/assets/images/PayCoPilotPic/GenSys1GeneratedInput.jpg",
    "srcset": "/assets/images/PayCoPilotPic/GenSys1GeneratedInput.jpg 672w",
    "width": 672,
    "height": 857
  },
  "/assets/images/PayCoPilotPic/GenSys3AnswerKeyOutputTest.jpg": {
    "src": "/assets/images/PayCoPilotPic/GenSys3AnswerKeyOutputTest.jpg",
    "srcset": "/assets/images/optimized/PayCoPilotPic/GenSys3AnswerKeyOutputTest-480.webp 480w, /assets/images/PayCoPilotPic/GenSys3AnswerKeyOutputTest.jpg 747w",
    "width": 747,
    "height": 822
  },
  "/assets/images/PayCoPilotPic/JsonObjectOfIngestedChunkAndVector.jpg": {
    "src": "/assets/images/PayCoPilotPic/JsonObjectOfIngestedChunkAndVector.jpg",
    "srcset": "/assets/images/optimized/PayCoPilotPic/JsonObjectOfIngestedChunkAndVector-480.webp 480w, /assets/images/PayCoPilotPic/JsonObjectOfIngestedChunkAndVector.jpg 987w",
    "width": 987,
    "height": 692
  },
  "/assets/images/PayCoPilotPic/RunBookAndPolicyPDFs.jpg": {
    "src": "/assets/images/PayCoPilotPic/RunBookAndPolicyPDFs.jpg",
    "srcset": "/assets/images/PayCoPilotPic/RunBookAndPolicyPDFs.jpg 511w",
    "width": 511,
    "height": 842
  },
  "/assets/images/PayCoPilotPic/copilot0WorkQue.jpg": {
    "src": "/assets/images/PayCoPilotPic/copilot0WorkQue.jpg",
    "srcset": "/assets/images/optimized/PayCoPilotPic/copilot0WorkQue-480.webp 480w, /assets/images/PayCoPilotPic/copilot0WorkQue.jpg 975w",
    "width": 975,
    "height": 852
  },
  "/assets/images/PayCoPilotPic/copilot1StartInvestigation.jpg": {
    "src": "/assets/images/PayCoPilotPic/copilot1StartInvestigation.jpg",
    "srcset": "/assets/images/optimized/PayCoPilotPic/copilot1StartInvestigation-480.webp 480w, /assets/images/PayCoPilotPic/copilot1StartInvestigation.jpg 932w",
    "width": 932,
    "height": 826
  },
  "/assets/images/PayCoPilotPic/copilot2InvestigationWorkplace.jpg": {
    "src": "/assets/images/PayCoPilotPic/copilot2InvestigationWorkplace.jpg",
    "srcset": "/assets/images/PayCoPilotPic/copilot2InvestigationWorkplace.jpg 705w",
    "width": 705,
    "height": 867
  },
  "/assets/images/PayCoPilotPic/copilot3ServiceErrorEvidence.jpg": {
    "src": "/assets/images/PayCoPilotPic/copilot3ServiceErrorEvidence.jpg",
    "srcset": "/assets/images/PayCoPilotPic/copilot3ServiceErrorEvidence.jpg 717w",
    "width": 717,
    "height": 717
  },
  "/assets/images/PayCoPilotPic/copilot4RAGRunBookMatch.jpg": {
    "src": "/assets/images/PayCoPilotPic/copilot4RAGRunBookMatch.jpg",
    "srcset": "/assets/images/PayCoPilotPic/copilot4RAGRunBookMatch.jpg 722w",
    "width": 722,
    "height": 837
  },
  "/assets/images/PayCoPilotPic/copilot5RAGPolicyMatch.jpg": {
    "src": "/assets/images/PayCoPilotPic/copilot5RAGPolicyMatch.jpg",
    "srcset": "/assets/images/PayCoPilotPic/copilot5RAGPolicyMatch.jpg 637w",
    "width": 637,
    "height": 810
  },
  "/assets/images/PayCoPilotPic/copilot6GenReport1.jpg": {
    "src": "/assets/images/PayCoPilotPic/copilot6GenReport1.jpg",
    "srcset": "/assets/images/PayCoPilotPic/copilot6GenReport1.jpg 737w",
    "width": 737,
    "height": 852
  },
  "/assets/images/PayCoPilotPic/copilot7GenReport1Continued.jpg": {
    "src": "/assets/images/PayCoPilotPic/copilot7GenReport1Continued.jpg",
    "srcset": "/assets/images/PayCoPilotPic/copilot7GenReport1Continued.jpg 622w",
    "width": 622,
    "height": 866
  },
  "/assets/images/PayCoPilotPic/copilot8HITLDecision.jpg": {
    "src": "/assets/images/PayCoPilotPic/copilot8HITLDecision.jpg",
    "srcset": "/assets/images/PayCoPilotPic/copilot8HITLDecision.jpg 646w",
    "width": 646,
    "height": 637
  },
  "/assets/images/PayCoPilotPic/copilot9AuditTimeline1.jpg": {
    "src": "/assets/images/PayCoPilotPic/copilot9AuditTimeline1.jpg",
    "srcset": "/assets/images/PayCoPilotPic/copilot9AuditTimeline1.jpg 627w",
    "width": 627,
    "height": 771
  },
  "/assets/images/PayCoPilotPic/copilot9AuditTimeline2Continued.jpg": {
    "src": "/assets/images/PayCoPilotPic/copilot9AuditTimeline2Continued.jpg",
    "srcset": "/assets/images/PayCoPilotPic/copilot9AuditTimeline2Continued.jpg 627w",
    "width": 627,
    "height": 822
  },
  "/assets/images/cgPic.JPG": {
    "src": "/assets/images/cgPic.JPG",
    "srcset": "/assets/images/cgPic.JPG 400w",
    "width": 400,
    "height": 400
  },
  "/assets/images/fuji-water-fallback.jpg": {
    "src": "/assets/images/fuji-water-fallback.jpg",
    "srcset": "/assets/images/optimized/fuji-water-fallback-480.webp 480w, /assets/images/fuji-water-fallback.jpg 1920w",
    "width": 1920,
    "height": 1080
  }
};
